### ISSUE TITLE
the sum (C)

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/no_term#1]
Partendo dal presupposto che le variabili le chiami come vuoi, ma fopen() non restituisce uno stream, ma un file descriptor

**Comment by Giandomenico-bit** [comment]
si infatti restituisce un puntatore ad una struttura di tipo FILE. Si ho sbagliato nominare la variabile, ora correggo

**Comment by FabioZTessitore** [comment]
se il file non c'è ipotizziamo che il valore iniziale sia zero

**Comment by Giandomenico-bit** [comment]
quindi devo inizializzare la variabile valueinfFile?

**Comment by FabioZTessitore** [comment]
Ci sono varie possibilità. Prova

Il gio 28 nov 2019, 12:37 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
se il file non esiste, il tuo programma stampa il messaggio di errore ed esce. Non è il comportamento voluto

**Comment by Giandomenico-bit** [comment]
forse ho capito
